# Generated by Django 5.0.4 on 2024-06-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_meets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='fields',
            field=models.CharField(blank=True, choices=[('Science', 'Science'), ('Commerce', 'Commerce'), ('Arts', 'Arts'), ('Humanity', 'Humanity')], default='Science', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='qualification',
            field=models.CharField(blank=True, choices=[('NONE', 'NONE'), ('PhD', 'PhD'), ('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('MBA', 'MBA'), ('B.Com', 'B.Com'), ('M.Com', 'M.Com'), ('BBA', 'BBA'), ('MBBS', 'MBBS'), ('MS', 'MS'), ('MD', 'MD'), ('LLB', 'LLB')], default='NONE', max_length=30, null=True),
        ),
    ]
